In [1]:
# 가상의 데이터
import numpy as np
X=2*np.random.rand(100,1) # 균일분포 U(0,1)에서 100*1의 matrix 생성
Y=4+3*X+np.random.randn(100,1) #표준정규분포로부터 100*1의 matrix 생성

# 모든 샘플에 x0=1 추가
Xb=np.c_[np.ones((100,1)),X]

import pandas as pd
pd.DataFrame(Xb)

      0         1
0   1.0  1.702324
1   1.0  1.425617
2   1.0  1.595950
3   1.0  1.207776
4   1.0  1.601041
..  ...       ...
95  1.0  0.278815
96  1.0  1.969088
97  1.0  0.673422
98  1.0  1.294066
99  1.0  1.407992

[100 rows x 2 columns]

In [2]:
# dot() 메소드는 행렬곱을 위해 사용됨
# np.linalg.inv()는 역행렬을 구함
# Xb.T 는 Xb의 전치행렬(transpose)
theta_best = np.linalg.inv(Xb.T.dot(Xb)).dot(Xb.T).dot(Y)
theta_best

array([[3.81895286],
       [3.17341423]])

In [3]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg

lin_reg.fit(X,Y)
lin_reg.intercept_,lin_reg.coef_

(array([3.81895286]), array([[3.17341423]]))

In [4]:
import numpy as np
np.random.randn(2,1)

array([[-1.74035724],
       [ 1.33504383]])

In [5]:
# 배치 경사하강법
eta=0.1
n_iteration=1000
N=len(Y)

theta=np.random.randn(2,1) #세타(모수의 추정값,회귀계수의 추정값)의 초기값을 랜덤으로 지정

for _ in range(n_iteration):
    grad=2/N*Xb.T.dot(Xb.dot(theta)-Y)
    theta=theta-eta*grad
    
theta

array([[3.81895286],
       [3.17341423]])

In [6]:
# 확률적 경사 하강법
n_epochs=50
t0,t1=5,50

def learning_schedule(t):
    return t0/(t+t1)

theta=np.random.randn(2,1)

for epoch in range(n_epochs):
    random_idxes=np.random.choice(range(N),size=N,replace=False)
    
    for i,rd_id in enumerate(random_idxes):
        xi,yi=Xb[rd_id:rd_id+1],Y[rd_id]
        grad=2*xi.T.dot(xi.dot(theta)-yi)
        eta=learning_schedule(epoch*N+i)
        theta=theta-eta*grad
theta

array([[3.82225347],
       [3.17606176]])

In [7]:
from sklearn.linear_model import SGDRegressor
sgd_reg = SGDRegressor(max_iter = 1000, tol = 1e-3, penalty = None, eta0 = 0.1)
sgd_reg.fit(X, Y.ravel())
sgd_reg.intercept_, sgd_reg.coef_

(array([3.83309842]), array([3.19438202]))

In [8]:
# 미니배치 경사 하강법
n_epochs=1000
t0,t1=5,50

def learning_schedule(t):
    return t0/(t+t1)

theta=np.random.randn(2,1)

batch_size=5
num_batch=N//batch_size

for epocch in range(n_epochs):
    random_idxes=np.random.choice(range(num_batch),size=num_batch,replace=False)
    
    for i,rd_id in enumerate(random_idxes):
        xi, yi = Xb[rd_id*batch_size:(rd_id + 1)*batch_size], Y[rd_id*batch_size:(rd_id + 1)*batch_size]
        grad=2*xi.T.dot(xi.dot(theta)-yi)
        eta=learning_schedule(epoch*N+i)
        theta=theta-eta*grad
        
theta

array([[3.82017466],
       [3.17271645]])